### 前向き・後ろ向きアルゴリズム
状態系列$s_t$  $t=0,...,n$  
潜在変数(状態系列のラベル)$\omega_i$  $i=0,...,c$  
観測変数$x_k$  $k=0,...,m$  
遷移確率$a_{i,j}$  
出力確率:$b_{j,k}$  
初期確率$\rho_i$  
時刻tにおいて状態系列のラベルがiとなる確率$\alpha_t(i)$
#### 前向き
1. 初期化
$$
\alpha_1(i) = \rho_i b(\omega_i, x_1) \tag{i=1,2,...,c}
$$
2. 再帰的計算  
\begin{eqnarray}
\alpha_t(j) = [ \sum_{i=1}^c a_{t-1}(i) a_{ij} ] b(\omega_j,x_t) \\
(t=2,3,...,n) (j=1,2,...,c)
\end{eqnarray}
3. 確率の計算
$$
P(x) = \sum_{i=1}^c \alpha_n(i)
$$

#### 後ろ向き
1. 初期化
$$
\beta_n(i) = 1 \tag{i=1,2,...,c}
$$
2. 再帰的計算
$$
\beta_t(i) = \sum_{j=1}^c a_{i,j} b(\omega_j,x_{t+1}) \beta_{t+1}(j) \tag{t=1,2,...,(n-1)}
$$

In [106]:
import numpy as np
c = 3 #状態数
s = [ "w1", "w2", "w3" ] # 状態
m = 2                    # 出力数
v = [ "v1", "v2" ]       # 出力記号 

rho = np.array([0.3, 0.2, 0.4])
a = np.array([(0.8, 0.1, 0.1),(0.3, 0.3, 0.4),(0.1, 0.5, 0.4)])
b = np.array([(0.8, 0.2),(0.1, 0.9),(0.1,0.9)])

x = [ 1, 1, 1, 0 ]#観測データ
T = len(x) #系列数
#前向きアルゴリズム
#初期化
alpha = np.zeros((T,c))
alpha[0] = rho * b[:,x[0]]
#再帰的計算
for t in range(T):
    if t == 0:
        continue
    temp = 0
    for i in range(c):
        temp += alpha[t-1,i]*a[i]
    alpha[t] = temp*b[:,x[t]]

#後ろ向きアルゴリズム
#初期化
beta = np.zeros((T, c))
beta[-1] = 1
#再帰的計算
for r in range(T):
    t = T - 1 - r
    if t == T-1:
        continue
    temp = 0
    for j in range(c):
        temp += a[:,j]* b[j,x[t+1]] * beta[t+1]
    beta[t] = temp

In [107]:
alpha

array([[0.06      , 0.18      , 0.36      ],
       [0.0276    , 0.216     , 0.1998    ],
       [0.021372  , 0.150714  , 0.152172  ],
       [0.0620232 , 0.01234374, 0.01232916]])

In [108]:
beta

array([[0.076296, 0.147591, 0.117113],
       [0.2244  , 0.2139  , 0.1411  ],
       [0.66    , 0.31    , 0.17    ],
       [1.      , 1.      , 1.      ]])

In [75]:
X = np.zeros((8,3))
X[4:] = 1
for i in range(len(X[0])):
    if i == 0:
        continuezよ
    for x in range(len(X)):
        if token:
            X[x,i] = (X[x,i-1]+1)%2
            token = False
        else:
            X[x,i] = X[x,i-1]
            token = True


In [76]:
X

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.]])

### ビタビアルゴリズム
出力記号系列から観測できなかった状態系列を推定する  
→観測結果をもたらす状態家列としてどんな系列が最適か求める  
$\gamma_t(i)$：観測結果xが得られた元で，t回目のサイコロが$\omega_i$である確率
$$
\gamma_t(i) = P(s_t=\omega_i|x)
$$